---
- name: Create a ServiceNow Change Request
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # -- ServiceNow Connection Details --
    snow_instance: "dev282033"  # IMPORTANT: Change this to your instance name
    snow_username: "apiuser" # The service account user ID

    # -- BEST PRACTICE: Encrypt your password with Ansible Vault --
    # To create this encrypted string, run the following command in your terminal:
    # ansible-vault encrypt_string --ask-vault-pass 'YourSuperSecretPassword' --name 'snow_password'
    snow_password: '2dq!=d{,C*(W2[l9tz-y[]A&AkG;qNTw2^CZu<Bs9ZOz7>'

  tasks:
    - name: Create a new Normal Change Request in ServiceNow
      servicenow.itsm.change_request:
        # --- Instance and Authentication ---
        instance:
          host: "https://{{ snow_instance }}.service-now.com"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        # --- Change Request Details ---
        state: new
        type: normal  # Can be 'normal', 'standard', or 'emergency'
        short_description: "Install Antivirus Software on {{ morpheus['instance']['name'] }}"
        description: "This change was created by an Ansible playbook to apply security patches to web-server-01."
        assignment_group: "Cloud Operator Group" # IMPORTANT: This group must exist in your instance
        requested_by: "{{ snow_username }}" # Good practice to set the requester as the service account
        other:
          justification: "Applying critical OS patches is required to maintain security compliance."

      register: new_change_request

    - name: Display the new Change Request number
      debug:
        msg: "Successfully created Change Request {{ new_change_request.record.number }} in instance {{ snow_instance }}."
